### ISSUE TITLE
osx issues

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#350]
It seems OSX believes our application is "bad" because it's not "mux aware". 

I can't get a window now without first breaking in the debugger, then continuing. 

I think 90% chance this will not be reproducible, but 
1) we should figure out why OSX does not believe we are responsible.  

In other news, 
2) our app is now nameless in the OSX Activity Monitor, and 
3) it still (as always) shows up behind all the other windows when it is started.

Here is the relevant stack for 1:

```
16:18:24.5079 INFO GUIAPPLICATION.576 Loading Gui resource done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
^C
Program received signal SIGINT, Interrupt.
0x00007fff8c6fca1a in mach_msg_trap ()
(gdb) where
#0  0x00007fff8c6fca1a in mach_msg_trap ()
#1  0x00007fff8c6fbd18 in mach_msg ()
#2  0x00007fff85f7a29c in io_service_open_extended ()
#3  0x00007fff85f210a2 in IOServiceOpen ()
#4  0x00007fff93063f50 in CGLRestoreDispatchFunction ()
#5  0x00007fff9306442e in cglBadApplicationNotMuxAwareLockDown ()
#6  0x00007fff93064575 in cglBadApplicationNotMuxAwareLockDown ()
#7  0x00007fff93067705 in CGLChoosePixelFormat ()
#8  0x00007fff93066e0a in CGLChoosePixelFormat ()
#9  0x00007fff88362f3b in createPixelFormat ()
#10 0x00007fff88362ed3 in -[NSOpenGLPixelFormat initWithAttributes:] ()
#11 0x0000000100abf1c6 in juce::OpenGLContext::NativeContext::NativeContext ()
#12 0x0000000100abe986 in juce::OpenGLContext::CachedImage::CachedImage ()
#13 0x0000000100abd471 in juce::OpenGLContext::Attachment::attach ()
#14 0x00000001009addc8 in juce::Component::sendVisibilityChangeMessage ()
#15 0x00000001009ad9d5 in juce::Component::setVisible ()
#16 0x00000001002b9a17 in Visus::GLContext::GLContext ()
#17 0x00000001002c2231 in Visus::GLCanvas::Pimpl::Pimpl ()
#18 0x00000001002bbc90 in Visus::GLCanvas::GLCanvas ()
#19 0x00000001002b9f8c in Visus::GLDisplay::initialise ()
#20 0x0000000100253713 in Visus::GuiApplication::onInit ()
#21 0x000000010000759c in Visus::ViewerApplication::onInit ()
#22 0x00000001002580e1 in Visus::GuiApplication::Pimpl::initialise ()
#23 0x0000000100945a86 in juce::JUCEApplicationBase::initialiseApp ()
#24 0x0000000100a5704b in juce::JUCEApplication::initialiseApp ()
#25 0x00000001009458aa in juce::JUCEApplicationBase::main ()
#26 0x0000000100945823 in juce::JUCEApplicationBase::main ()
#27 0x0000000100007021 in main ()
```

**Comment by scrgiorgio** [comment]
"mux aware" ==?

**Comment by scrgiorgio** [comment]
Can you try this:

Switching off "Automatic graphics switching" in System Preferences/Energy Saver fixes the problem.

at least we know if this is the problem.

**Comment by scrgiorgio** [comment]
I updated Juce too.

**Comment by cchriste** [comment]
This is not reproducible though it may happen again. I'm closing the issue.
